# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97f87b0bd2b7100195e2b6eebfe98b045558a36ed5b0662cd7c7aa42458ab17b9e843c38a19275739fe802c2880fa5f2a0454ef09a106a76eca4c2d72969d27a

test:
  secret_key_base: 35b2ec72bda9c4d07cedb5f83ff0bd9f79982fae7c0e42d5f0c2e097cc15bab885c3444966fc1e840b2c79341da01f741819113dd440298d4db543d7ca071bec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
